# Generated by Django 3.2.5 on 2021-07-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsmodel',
            name='answer_1',
            field=models.CharField(default='yes', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionsmodel',
            name='answer_2',
            field=models.CharField(default='yes', max_length=200),
            preserve_default=False,
        ),
    ]
