# Generated by Django 3.2.5 on 2021-07-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_auto_20210706_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsmodel',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quizmodel',
            name='quiz_title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
