# Generated by Django 3.2.5 on 2021-07-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_auto_20210706_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsmodel',
            name='question_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
