# Generated by Django 3.2.5 on 2021-07-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_auto_20210708_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionsmodel',
            options={'permissions': (('can_edit_questions', 'can_edit_questions'), ('can_view_questions', 'can_edit_questions'), ('can_view_answers', 'can_view_answers'))},
        ),
    ]
